repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict

  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      # Comprehensive linting aligned with pyproject.toml configuration
      - id: ruff
        name: ruff-lint
        description: Run ruff linter with comprehensive checks
        args: [--fix, --exit-non-zero-on-fix]
        files: ^gal_friday/|^tests/

      # Code formatting
      - id: ruff-format
        name: ruff-format
        description: Run ruff formatter
        files: ^gal_friday/|^tests/

  # Type checking with MyPy (graduated enforcement)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: mypy-check
        description: Static type checking with MyPy
        args: [--ignore-missing-imports, --no-strict-optional]
        files: ^gal_friday/
        additional_dependencies: [types-requests, types-redis, types-setuptools]

  # Security scanning with Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit-security
        description: Security vulnerability scanner
        args: [-r, gal_friday/, -f, json, --skip, B101,B601]
        files: ^gal_friday/
