repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  # Memory leak detection - uses memory_profiler under the hood
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  # Local hooks - runs pytest in non-failing mode to generate reports
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        description: Run pytest to check for test failures without blocking commit
        entry: pytest --quiet --no-header --no-summary --cache-clear -xvs
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
        stages: [commit]
        # Don't block commit if tests fail, just report
        fail_fast: false
