-- Schema for the application logs table

CREATE TABLE IF NOT EXISTS logs (
    id BIGSERIAL PRIMARY KEY,                     -- Auto-incrementing primary key
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(), -- Timestamp with timezone
    logger_name VARCHAR(255) NOT NULL,            -- Logger name (e.g., gal_friday.ExecutionHandler)
    level_name VARCHAR(50) NOT NULL,             -- Log level name (e.g., INFO, WARNING)
    level_no INTEGER NOT NULL,                   -- Log level number (e.g., 20, 40)
    message TEXT NOT NULL,                       -- The main log message
    pathname TEXT,                               -- Full path of the source file
    filename VARCHAR(255),                       -- Filename part of the source file
    lineno INTEGER,                              -- Line number in the source file
    func_name VARCHAR(255),                      -- Name of the function/method
    context_json JSONB,                          -- Structured context data (nullable)
    exception_text TEXT                          -- Full exception traceback (nullable)
);

-- Optional: Add indexes for faster querying on common fields
CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON logs (timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_logger_name ON logs (logger_name);
CREATE INDEX IF NOT EXISTS idx_logs_level_name ON logs (level_name);

-- Optional: Comment on table and columns for clarity
COMMENT ON TABLE logs IS 'Stores application log records generated by the LoggerService.';
COMMENT ON COLUMN logs.timestamp IS 'Timestamp when the log record was created (UTC recommended).';
COMMENT ON COLUMN logs.logger_name IS 'Name of the logger instance that created the record.';
COMMENT ON COLUMN logs.level_name IS 'Human-readable logging level (e.g., INFO, ERROR).';
COMMENT ON COLUMN logs.level_no IS 'Numeric logging level.';
COMMENT ON COLUMN logs.message IS 'The primary log message.';
COMMENT ON COLUMN logs.pathname IS 'Full path to the source file where the logging call occurred.';
COMMENT ON COLUMN logs.filename IS 'Filename part of the source file.';
COMMENT ON COLUMN logs.lineno IS 'Line number in the source file where the logging call occurred.';
COMMENT ON COLUMN logs.func_name IS 'Name of the function or method where the logging call occurred.';
COMMENT ON COLUMN logs.context_json IS 'Optional structured context data provided with the log message (JSONB format).';
COMMENT ON COLUMN logs.exception_text IS 'Full exception traceback if an exception was logged.';
